---
title: "Effects of stockholding policy on consumer price: Evidence from Zambia"
author: "Yujun Zhou"
date: "January 25, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
## Introduction 

Volatile food prices can bring about economic and civil unrest ( Bellemare 2015; Fjelde 2014; Weinberg and Bakker 2015). In particular, households are vulnerable to price hikes for staple commodities. Many developing countries have intervened in their domestic agricultural markets to stabilize food prices, through domestic food subsidies, stockholding policies and export bans. While many authors (Martin and Anderson 2012) argue that these policies can have negative effects for trade partners, little work explores their effect on domestic food price volatility.

In this paper, we look at the effect of stabilizing policies in Zambia on the local maize price. As the major food staple, maize provides almost sixty percent of Zambians’ calorie intake . Therefore, reducing price fluctuations has been an important policy goal for Zambia where food represents about fifty percent of the household budget (Mason and Jayne 2009). 

Maize prices are vulnerable to domestic production shocks as well as international price movements driven by world supply and demand. Domestically, volatile rainfall and a lack of irrigation systems lead Zambia to experience a poor harvest about once in every three years (Dorosh 2009). External shocks to domestic maize prices can also pose a threat to the already compromised food security in the country. During the 2007/08 food crises, when the international maize price reached exceptionally high levels, the Zambia maize retail price increased more than fifty percent on average compared to the previous year (Minot 2011).  

The government of Zambia has repeatedly imposed bans on maize exports as a price stabilizing measure since the 1960’s. In the past two decades, Zambia restrained the issuance of export permits in 2002, 2005, 2008 and the end of 2013 to ensure domestic food security and access to food in times of maize production deficit. How effective is the export restriction at stabilizing local maize prices and isolating the domestic market from external price shocks from trade partners like Republic of South Africa (major producer of excess maize in Southern Africa)? The purpose of this research is to explain the maize price volatility in Zambia, by taking into account the domestic drought spells, policy changes, and external market shocks. In particular, this research seeks evidence on whether export bans can alleviate local price variability.

In theory, export bans can decrease price volatility generated by supply or demand shocks, which explains the prevalent and repeated use of such policies in recent years. Porteous (2012) argues that bans usually imply a significant rise in the cost to move the goods to the border. By lowering the export parity, the ban prevents the high international price from transmitting to the domestic market and also adds to the local grain supply. In this way, the export ban is expected to reduce domestic price fluctuations. Using a dynamic model, Gouel and Jean (2012) show that an optimal food price stabilization policy should involve some restrictions on exports. They argue that the price soothing effect generated through buffer stocks would leak to the external market when there is both a domestic production shock and an international price spike. This theory fits into the current situation in Zambia. The Food Reserve Agency in Zambia, established in 1996, has supported domestic maize prices received by farmers and holding maize stocks in case of production shortages (Govereh, Jayne, and Chapoto 2008).

If stabilizing policies are pursued in an unpredictable manner, the uncertainty in the policy itself may intensify rather than mitigate price volatility (Apergis and Rezitis 2011). Chapoto and Jayne (2009a) suggest that Zambia’s discretionary trade restriction and marketing policies may be the reason behind its higher degree of price volatility compared to neighboring countries, as these policies make the market unpredictable. Jayne (2012) concludes that in Eastern and Southern Africa, governments’ attempt to stabilize maize price often lead to unstable prices, and are particularly unable to prevent high food prices. Martin and Anderson (2012) find that the trade barriers imposed by governments are not helpful in maintaining stable food prices in the domestic market. Other studies suggest that participation in free trade, instead, can set both a lower bound and a price ceiling for staple prices, that in turn, decrease price volatility (Govereh, Jayne, and Chapoto 2008; García-Germán et al. 2013). 

This paper seeks to provide empirical evidence on the effects of export bans on the maize price variability in Zambia using retail maize price data from 2003 to 2016. To capture possible volatility transmission from South Africa, a multivariate generalized autoregressive conditional heteroskedastic (MGARCH) model is used. The model includes both a drought index and an export ban indicator as exogenous variables in the conditional variance equation.

This paper makes the following contributions to the literature. First, the MGARCH model with exogenous variables allows for both the influence of external market and domestic weather shocks. Given that Zambia relies on maize imports from South Africa in times of food shortage (Myers and Jayne 2012), it is plausible to assume that physical trade transmits volatility. Previous studies focus either on the local market conditions and on government policies (Chapoto and Jayne 2009b) or on the volatility spillovers from the international market (Rapsomanikis and Mugera 2011). Second, the model identifies the effect of the ban by controlling for weather shocks. Variations in agricultural yields is an essential part of agricultural price variation (Gilbert and Morgan 2010). Weather-induced production shocks usually motivate the implementation of export bans. Ignoring the weather effects will lead to biased estimates of the influence of the export ban. Despite authors who argue that discressionary trade policies may generate higher price volatility (Rapsomanikis and Mugera (2011) and Sassi (2015)), the frequent changing policy and unpredictable policy environment are likely to be the result of production shocks or price hikes from the international market. Hence, these studies may overestimate the effects of export bans on price volatility. Third, the drought index used in this paper offers a more accurate measure of drought in the country than the precipitation index used in previous papers, as it is based on cropland area compared to using .    
Understanding the nature and the changes in price variability is essential to ensure political and social stability in developing countries (García-Germán et al. 2013). Mitigating the effects of price instability on smallholder farmers and rural consumers has been longstanding concerns of developing countries. This paper provides empirical evidence on how governments’ efforts intervening in agricultural trade may have affected price volatility. Research results have relevant policy implications and can guide future domestic policies aiming at improving domestic food security.  

The paper is structured as follows. Section 2 gives background information on the Zambia maize market and relevant policies. Section 3 illustrates the empirical strategy by describing the conditional mean and conditional variance used in the MGARCH model. Section 4 includes description of data and a discussion of the empirical results. Section 5 concludes with the main findings of the paper and relevant policy implications. 


## Background

Zambia ranks 139 out of 188 countries in the 2015 UNDP Human Development Report and is classified as a lower middle-income country by the World Bank (Cammelbeeck 2015). With sixty percent of its population below the poverty line and almost fifty percent malnourished, the country suffers from a prevalent poverty and food insecurity (Sitko et al. 2011). 

The agricultural sector in the country comprises of roughly 1.5 million smallholders and 2,000 large-scale farmers. More than ninety percent of maize productions and eighty percent of total maize sales come from smallholder farms (Tembo et al. 2009). Maize production is not evenly distributed across farms. Around two percent of the small and medium farmers generate roughly half of maize output. A large number of small farm households are still net buyers of maize (Sitko et al. 2011). The dependence on the volatile rainfall and a lack of irrigation systems make the agricultural output extremely unstable. Years of drought, flood, and insufficient input supply, which represent on average one year out of three, lead to deficient maize production to satisfy food demand at the national level (Dorosh, Dradri, and Haggblade 2009). Since weather shocks are localized, certain production regions experience more severe shocks than others. Substantial production shortages result in the domestic maize price rising to the Republic of South Africa’s maize import parity (Myers and Jayne 2012). Trade is thus a potential valuable tool to stabilize the domestic price. 

However, past maize price fluctuations and the consequent social unrest have led the government of Zambia to believe food prices are far too strategically and politically important to leave to the market (Chapoto 2012). The government mistrusts private traders in their ability to bring in enough maize to stabilize the market (Myers and Jayne 2012). Private traders, on the other hand, blame the government for implementing unpredictable policies on tariffs, import licenses, and maize import subsidies. Short-term export bans are often imposed to restrict maize outflows to ensure food security and access to food when the country experiences a maize production deficit. These export bans are often carried out in an ad-hoc, stop-go nature (Chapoto & Jayne 2009). The effects of export bans on domestic price volatility are not clear. While in some countries such as India, export bans appear to have decreased prices and price volatility (Baylis, Jolejole-Foreman, and Mallory 2013), in other countries such as Russia the restriction on exports actually increases the food price at the exporting market because of a higher transaction cost (Porteous 2012; Welton 2011).  

Stockholding is expensive for poor economies, which makes trade the usual alternative. However, the uncertainties in imports and the transmission of shocks from other countries makes trade a less reliable tool to address domestic food shortage. Besides, storage is needed to supply the market before imports arrive. Consequently, developing countries have been rethinking their policies on grain storage and dependence on international trade to secure domestic food security (Dorosh 2009). There were reports of Zambia traders suggesting to the government the existence of sufficient amount of local stocks, which would make maize imports unnecessary (Chapoto 2012). However, the series of agricultural and trade policies that the government of Zambia has conducted in the recent years suggest a turn to the option of building more grain stocks. 

The Food Reserve Agency (FRA) was established in 1996 with the aim of building and managing national grain stocks (Govereh, Jayne, and Chapoto 2008). The buffer stocks are intended to stabilize maize price and provide available maize supply to the market. The FRA purchases substantial maize from small households in various geographic regions since the 2003/04 marketing year (corresponding to the study period in this paper). The high pan-territorial buying price (uniform price in ) makes the FRA the dominant buyer in the market (Mason and Myers 2013). In 2006 and 2007, the FRA bought more than half of the surplus maize by smallholder farmers (Ricker-Gilbert et al. 2013), which helps to build higher maize stocks. In part to protect the dominant market position of the FRA, the government implemented a series of policies including export bans, import tariffs, and imports through the FRA (Tschirley and Jayne 2010). According to grain traders, millers also get subsidized maize stocks from FRA. These measures to build higher stocks have led the national maize stocks to reach historically high levels after 2009 (shown in Figure 1). But the stock building comes at a considerable financial cost. The procurement and selling of maize at subsidized prices along with the input subsidies account for over 43% of the total agricultural budget (Nkonde et al. 2011). 

## Method 

This paper tries to find the effects of stockholding policy in Zambia on the maize price level and volatility. The study period is Jan.2003 - Nov. 2009, when have both the market price, FRA buying/selling price and purchase quantity by district. We are comparing district maize price with FRA purchases in the same month with markets that don't have FRA purcase at all. 

The endogeneity issue at hand is multiple. First, several policies were at play and all to a certain degree endogenous to grain production and maize prices, including temporary export ban, import tariff and input subsidy program. Much of this is time variant and work on all the markets (control and treatment) alike, and can be controlled by adding in the policy variable when the policies are in place. Also by adding in the weather shocks in the previous year.

Second, the pricing and purchase quantity of the FRA is endogeous to the local prices, which can be controlled by weather shocks at the local level. Local price matters because of the incomplete infrastrature and a lack of market information system. 

The source of variation are seasonal price changes, across year production/stock changes, across year policy changes and across markets price differences within the same year. 

The identification strategy is to make use of the step by step roll out of the FRA throughout the years. The intensity of treatment is measured in terms of FRA purchase as % of smallholder maize sales at the district level, No. of districts they are buying (as it affects to the price transmission and price expectation). 

The variables of interest are maize price levels, price spread between district market and Lusaka, and coefficient of variation of district level maize price.

The model would be consisted of a structural VAR with one equation as the price to policy and weather, and one equation as the policy to price. But esitmate the equation with a reduced form using OLS. a test between a structural break VAR and a linear VAR

test for threshold 

The usually time-varying and clustering nature of commodity price volatility can be modeled through the use of generalized conditional heteroskedasticity models (GARCH) (Chou, 1988). Developed by Engle (1982) and Bollerslev (1986), GARCH models contemporary and future volatilities as a function of past volatility and past market shocks.To measure maize price volatility in Zambia by allowing for the influence of South Africa’s maize market, a major trading partner, a multivariate GARCH (MGARCH) model is used. Minot (2014) supports the use of a GARCH model over the traditional measure of the coefficient of variation (CV) because the latter depends on the length of the sample when the prices are nonstationary.

Despite the widespread use of GARCH models in the financial economics literature, its application to food price analysis is relatively recent, and has gained special relevance since the increased agricultural commodity price instability during the second half of the 2000s. Gilbert and Morgan (2010) use a GARCH model to estimate the conditional volatility of various grain prices in the international market. Rapsomanikis and Mugera (2011) apply the GARCH model to assess the spillover effects from the international markets to Ethiopia, India and Malawi. Sassi (2015) estimates the conditional volatility of maize price in Malawi using a VEC-GARCH approach. 

This article fits a MGARCH to Zambia and South Africa maize prices and considers weather and policy measures as exogenous variables that can also influence price instability. In a preliminary analysis of the data, unit root tests show that both prices are nonstationary. The Johansen cointegration analysis (Johansen 1988; Johansen and Juselius 1990), yielding a trace test value of 20.381(below the critical value of 25.731), suggests a lack of cointegration between Zambian and South African maize prices, a finding supported by previous research (Minot 2011; Myers and Jayne 2012).This may be explained by relatively high transportation costs and government intervention. Hence, any links between the two prices can be exclusively attributed to the short-run dynamics. These can be assessed through a Vector Autoregressive (VAR) of the first-differenced maize prices as follows: 


where ∆Pt is a vector of maize prices in first differences at time t. ∆Pt-k represents the first lag of ∆Pt. matrix of coefficients measuring own and cross autoregressive price effects.  vectors containing the model intercepts and seasonal indicators, respectively.   are (2 1) vectors containing the exogenous variables like the weather index and the policy variables.   is a ( vector of i.i.d. errors. In other words, the conditional mean model explains maize prices as a function of their own lag, past prices in the other market,seasonal and policy variables.
In order to assess volatility spillovers across the two markets considered, the conditional volatility model is specified in terms of a Baba–Engle–Kraft–Kroner GARCH (Engle and Kroner 1995) parametrisation. The BEKK specification guarantees the covariance matrix to be positive semidefinite while maintaining a relatively parsimonious presentation. Following the model set up in Serra and Gil (2013), the conditional variance model can be expressed in matrix form as follows:


where   is the estimate of the residuals’ variance–covariance matrix. Matrix   is a   matrix that relates past market shocks to current price volatility, while  matrix that captures the autoregressive effect of volatility. The influence of exogenous variables can be allowed for through matrix   in (2) (Moschini and Myers, 2002). In this paper  , where  ,   and   representing two exogenous variables influencing maize price volatility: Zambia/South Africa weather conditions, and   a parameter vector. A more detailed presentation of the GARCH model used in the empirical application is offered in Table 4. 
Equation 2 models conditional volatilities as a function of past price shocks and past volatility in South African and Zambian markets. The effects of the exogenous variables enter the volatility equation in quadratic or interaction terms. Following Rai (2012) and Saraidaris et al. (2010) and in contrast to Caporale, Spagnolo, and Spagnolo (2016), the export ban is introduced as an exogenous variable in the volatility model . The reason for such specification is because the export ban is usually temporary and used repeatedly over time. 

 
## Empirical Application 

The empirical application is based on the following data. First, monthly Zambia and South Africa maize prices observed from Jan. 2003 to Feb. 2016 are considered. The Zambia price is the maize retail price in Lusaka, the capital of the country. Price data were collected by the World Food Program and the Central Statistical Office in Zambia. The South Africa Futures Exchange (SAFEX) cash price from the Johannesburg Stock Exchange is used as the South Africa maize price. Prices are expressed in Zambian Kwacha with exchange rates between South African Rand and Zambian Kwacha derived from the South African Reserve Bank. Figure 2 shows a plot of Lusaka maize price and South Africa maize prices, as well as the amount of net import of maize from South Africa. 

To separate possible weather shocks from the influence of policy changes, a monthly drought index was built for both Zambia and South Africa. This drought index is expressed in the form of soil moisture percentile: the lower the index, the more severe the drought in the area. The drought index is a more accurate and complete measure of drought compared to the precipitation measure used in Dorosh (2009) and Chaopoto and Jayne (2009b). Since the objective of this paper is about the effect of weather shocks on agricultural production, the index is calculated as an average of all the cropland area in both countries. The soil moisture grid data comes from the African Drought Monitor website. Cropland area data are collected from the Center for Sustainability and the Global Environment (SAGE) dataset. 

The seasonal variables are constructed based on the autocorrelations analysis of maize price in Zambia and the RSA. It appears that a six-month lag and an eleven-month to be most relevant. The export ban indicator is one when there is a maize export ban in place. Table 1 presents the list of time and durations of export ban in Zambia. However, the export ban in March 2007 is not included because it is less than a month .

Tests for unit roots for the variables used in the VAR model are shown in Table 2. To assess the order of integration of those series, the Augmented Dickey-Fuller (ADF) and Phillips and Perron (PP) tests are applied . Both tests suggest that maize prices in Zambia and South Africa have a unit root (PP test marginally rejects the null for the Zambia price at 10%). Test results on the price series in first differences reject the null at 5%. Therefore, the two price series are clearly integrated of order 1 (or I(1) process). As mentioned earlier, maize prices in Zambia and South Africa are not cointergrated according to the Johansen cointegration test. This suggests that there is not a long run equilibrium between the two markets. Unit root tests on the Drought Indices in Zambia and South Africa are found to be stationary with both tests rejecting the null at 5% level, so does the other policy variables.  
Table 3 presents summary statistics of the variables used in the analysis. According to these statistics, monthly changes in the South Africa price are bigger than the monthly changes in the Zambia price. The drought index in Zambia shows that the cropland in Zambia is slightly more humid than that in South Africa, but it also changes more dramatically from month to month indicating a more volatile rainfall.

As is explained in the model section, a VAR-GARCH model with exogenous variables is estimated to assess the Zambia maize price volatility by domestic weather shocks, policy influence, and shocks transmitted from external markets. The conditional mean and conditional volatility models are jointly estimated by maximum likelihood techniques and parameter estimates are presented in Table 4. Based on the Akaike information criterion, the optimal lag for the conditional mean model is 2. Results show evidence of short-term price spillover effects between the two markets: cross-effects with two lags are statistically significant in both equations, which is expected given the trade flows between the two markets. 

The conditional mean model does not include many of the possible candidate of other exogenous variables in this regression such as exchange rate, high stock indicator, import/export quantity, oil prices and even the export ban dummy itself because there are not statistically significant in the mean model. Another reason for this is that the data availability for capturing perfectly of the changes in policy on FRA purchase, input subsidy on a monthly level. The amount of purchase of FRA is only available on a yearly basis for some markets. Similarly, the stock level data is only at a yearly frequency. The use of a high stock indicator (equals to one after the year 2010) is not showing much influence on the changes of price from month to month either. In addition, because of the vast number of parameters to be estimated using the VAR-BEKK-GARCH method, the inclusion of too many exogenous variables usually cause non-convergence problem in the estimation process. 

The conditional variance models allow for the influence of weather shocks captured by the Zambia and South Africa drought indices, as well as the indicator for the export bans. The drought indices are lagged two months to allow the market to respond to changing weather conditions. However, different choices of lags in the drought index don’t change the results substantially. Lagrange Multiplier (LM) tests show that there are no remaining ARCH effects in the residuals after filtering for GARCH effects. Further, residuals do not show any remaining autocorrelations according to the Ljung-Box Q-statistic. 
In order to interpret the estimates of the GARCH parameters, conditional variance equations are derived and presented in Table 5. The Delta method was used to determine the standard error and statistical significance of the coefficients in Table 5. Results further suggest that the Zambia price volatility (h11t) is positively influenced by past market shocks in the domestic market  and in the international market  . In contrast, past volatility in Zambia (h11t) and in South Africa (h22t) do not have a significant influence on the current Zambia price volatility. In this regard, the South Africa market influences Zambia market price volatility only through its market shocks. In contrast, shocks to the Zambian market have no influence on South Africa price instability. However, the South Africa market price volatility is affected by volatility in Zambia and the covariance between the two markets.
Table 6 presents the marginal effects of the exogenous variables on conditional volatilities, calculated at the data means. The Zambia drought index negatively affects the volatility in Zambia and South Africa indicating that the volatility is higher when there is a drought. The effect is less severe in South Africa since it is a much bigger market. The marginal effect of Zambia government’s export ban on the conditional volatility in both Zambia and South Africa is negative, suggesting that the ban itself decreases maize price volatility instead of increasing it as is argued in Chapoto and Jayne (2009a). 
Predicted volatility for both markets is presented in Figure 3. As we can see, recent years have experienced increasing volatility. This is in line with increasing droughts in the Southern Africa area. The more frequent and increasingly severe drought spells in the area in the recent decade is possibly the main reason for this, along with the consequent increase market intervention. Also, the figure confirms the seasonal aspects of volatility mentioned in the previous studies. It shows that the conditional variance of maize price is higher during the lean season in February, March, and April. The seasonal effects are already taken care of in the mean model. 

## Conclusion
Among the wide variety of factors that affect staple foods’ price volatility, this paper focuses on the effect of government policy decisions that might exacerbate rather than lessen price instability. Following the previous literature on maize price volatility and policy interventions, the model incorporates the influence of weather induced production shocks, external market price transmission to separate the influence of trade policy. By controlling for the influence of weather shocks, the model is able to identify the effect of export bans on maize price variability in Zambia. 

A few interesting findings are derived from this empirical investigation. First, consistent with Dorosh (2009) and the volatility in Zambia is found to be persistently affected by domestic weather shocks which is captured by the drought index. Similar to the finding in (Minot 2014) and Gilbert and Morgan (2010), the domestic volatility is also influenced by the external market that they engage in trade with. The estimated volatility plot also agrees to the seasonal pattern of maize production and marketing found in previous papers.

Second, this study finds that after controlling for the effect of domestic weather shocks, trade intervention actually has a price stabilizing effect on the local price volatility. This result disagrees with the conclusion found by Chapoto & Jayne(2009), Rapsomanikis and Mugera (2011) stating that the export ban itself is increase the variability of prices. Rather, the frequent changing in policy, which is correlated with the incidence of drought spells, is behind the surging price volatility. The restriction on export itself is price stabilizing. 

There are limitations of this paper. Because of the incomplete or imperfect measure of other policies on maize, they are not included in the model because they show little influence on the prices. But it could be measurement error in modelling these other policies. Also, in addition to model export ban as a policy dummy, the use of total maize export in Zambia may be preferred, for the export quantity is a smoother measure across month. However, on monthly frequency, We can only obtain the export to the RSA. Besides, there are also potential unrecorded trade activities on the border that weakens the credibility of formal trade quantity 
data. 
	The result of this paper might be of interest to policy makers in the Southern Africa region where both trade restrictions and weather shocks are common. While Zambia has built significantly more maize stocks during the recent decade, it is still facing volatile food staple prices, which is extremely harmful to the poor people at the edge of secure food access. The restrictions on trade maybe a useful policy tool in combine Africa with stock building to stabilize prices. 














